# Generated by Django 5.0 on 2023-12-29 16:12

import django.contrib.postgres.fields
import django.db.models.deletion
import order365.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Configurations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('badIp', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), default=list, size=None)),
                ('badCidr', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), default=list, size=None)),
                ('badDomain', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=256), default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Binder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('user', models.ForeignKey(default=order365.models.get_default_user, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('binderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='order365.binder')),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('ipswitches', models.JSONField(blank=True, default=dict, null=True)),
                ('file', models.FileField(blank=True, upload_to='order365/uploads/')),
                ('dataDoct', models.JSONField(blank=True, default=dict, null=True)),
                ('folderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='order365.folder')),
            ],
        ),
    ]
