# Generated by Django 5.0 on 2023-12-31 22:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order365', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configurations',
            name='domainIngestion',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=256), default=list, size=None),
        ),
        migrations.AddField(
            model_name='configurations',
            name='ipIngestion',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(max_length=256), default=list, size=None),
        ),
        migrations.AddField(
            model_name='file',
            name='ipWhois',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
