# Generated by Django 5.0 on 2024-01-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order365', '0003_remove_file_ipwhois_remove_file_ipswitches_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='userLocation',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
