# Generated by Django 5.0 on 2024-01-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order365', '0005_folder_usermap'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='ipWhois',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='privledgeActiveUser',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='threatIp',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='userActive',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='userList',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='userLocation',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='userMap',
            field=models.FileField(blank=True, upload_to='./order365/maps/'),
        ),
        migrations.AddField(
            model_name='file',
            name='userSignCount',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, upload_to='./order365/uploads/'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='userMap',
            field=models.FileField(blank=True, upload_to='./order365/maps/'),
        ),
    ]
