# Generated by Django 5.0 on 2024-01-08 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order365', '0007_alter_file_file_alter_file_usermap_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='binder',
            options={'permissions': [('view_mymodel', 'Can view my model')]},
        ),
        migrations.AlterModelOptions(
            name='folder',
            options={'permissions': [('view_mymodel', 'Can view my model')]},
        ),
        migrations.AlterField(
            model_name='binder',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(blank=True, upload_to='./order365/static/uploads/'),
        ),
        migrations.AlterField(
            model_name='file',
            name='userMap',
            field=models.FileField(blank=True, upload_to='./order365/static/maps/'),
        ),
        migrations.AlterField(
            model_name='folder',
            name='userMap',
            field=models.FileField(blank=True, upload_to='./order365/static/maps/'),
        ),
    ]
